CREATE DATABASE KirkRoerig;
USE KirkRoerig;

CREATE TABLE IF NOT EXISTS Articles (
	id     MEDIUMINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	posted DATETIME NOT NULL,
	file   VARCHAR(256)
);

CREATE TABLE IF NOT EXISTS Categories (
	id   MEDIUMINT UNSIGNED NOT NULL,
	name VARCHAR(32)
);

CREATE TABLE IF NOT EXISTS Projects (
	id   MEDIUMINT UNSIGNED NOT NULL,
	project VARCHAR(32)
);
